### ISSUE TITLE
请问大佬，我可以将我自己的数据库套用到此项目吗？

### ISSUE THREAD

**Issue by K0zero** [ShawnHXH/QA-CivilAviationKG#3]
因为大佬项目的内容太丰富了，所以我想知道我如果把我自己的neo4j图数据库套用的话，需要修改什么呢？

我的数据库主体是人，是一个人际关系展示的图数据库。

提前感谢大佬。

**Comment by K0zero** [comment]
不过我不打算使用那个自动问答的功能，就只想做一个可视化和几个基本的查询功能，请问该怎么做呢

**Comment by shawnh2** [comment]
将你自己的数据库导入到 neo4j 后，基本的查询功能使用 py2neo 提供的几个接口就可以实现

**Comment by K0zero** [comment]
但是我使用项目代码连接到自己的数据库中后，主界面本应该显示数据库，但我这里是空白，请问这是什么情况呢？
我除了修改数据库账户信息，其他的没有改
![image](https://user-images.githubusercontent.com/57054783/184061487-86d26872-e921-4ffa-a243-ce9187e606d7.png)

**Comment by shawnh2** [comment]
这个界面是问答页面不是数据库页面，这个项目是专门针对民航业数据知识图谱设计的，不支持其他类型的图数据，因为它们的关于结点和边的定义与属性都不一样。

**Comment by K0zero** [comment]
> 这个界面是问答页面不是数据库页面，这个项目是专门针对民航业数据知识图谱设计的，不支持其他类型的图数据，因为它们的关于结点和边的定义与属性都不一样。

原来是这样, 怪我没好好仔细看这个项目 还以为能有个数据库界面的。 谢谢大佬解答。
